# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик в сауне"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/5/
Content-Type: application/json

{
  "description": "2й Датчик в сауне"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 5,
  "temperature": 66
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/4/
Content-Type: application/json
